### ISSUE TITLE
SyntaxError: Use of const in strict mode.

### ISSUE THREAD

**Issue by jnarowski** [luandro/hapi-universal-redux#78]
Got this error when trying to boot...

[piping] can't execute file: /Users/johnpaulnarowski/Dev/projects/hapi-universal-redux/babel.server.js
[1] [piping] error given was: /Users/johnpaulnarowski/Dev/projects/hapi-universal-redux/node_modules/hapi/lib/index.js:5
[1] const Server = require('./server');
[1] ^^^^^
[1] SyntaxError: Use of const in strict mode.
[1]     at exports.runInThisContext (vm.js:73:16)
[1]     at Module._compile (module.js:443:25)
[1]     at Module._extensions..js (module.js:478:10)
[1]     at Object.require.extensions.(anonymous function) [as .js](/Users/johnpaulnarowski/Dev/projects/hapi-universal-redux/node_modules/babel-core/lib/api/register/node.js:214:7)
[1]     at Module.load (module.js:355:32)
[1]     at Module._load (module.js:310:12)
[1]     at Function.module._load (/Users/johnpaulnarowski/Dev/projects/hapi-universal-redux/node_modules/piping/lib/launcher.js:32:16)
[1]     at Module.require (module.js:365:17)
[1]     at require (module.js:384:17)
[1]     at Object.<anonymous> (/Users/johnpaulnarowski/Dev/projects/hapi-universal-redux/src/server.js:7:13)
[1] [piping] further repeats of this error will be suppressed...
[1] [piping] File src/server.js has changed, reloading.
[1] [piping] File babel.server.js has changed, reloading.

**Comment by luandro** [comment]
Hapi 11 requires Node >= 4.0.0. Will add to the README.
